### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [dcdepaepe/tc359_forms#1]
One of the few projects I haven't been able to immediately break! _And_ also one of the best-looking! While it does work though, I do see some inconsistent indentation in `app.rb` that I'd like you to fix. The [resources on this page](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) should be helpful here.

Let me know if you encounter any difficulties with that and I'll be happy to hop on a screenshare!

**Comment by dcdepaepe** [comment]
Done and done! Thanks. I've been trying to track these down but every time I open sublime it goes back to tab: 4 so I sometimes miss it.

**Comment by chrisvfritz** [comment]
:+1: Looking good! You can [change the settings in sublime permanently like this](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md#global) if you want.
